// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDescekWWnJEVPdroRFUc3-RSPFhw8GzvQ',
    appId: '1:286230054282:web:9b7e5ca06bce0944a4f473',
    messagingSenderId: '286230054282',
    projectId: 'giziku-mobile',
    authDomain: 'giziku-mobile.firebaseapp.com',
    storageBucket: 'giziku-mobile.firebasestorage.app',
    measurementId: 'G-JL8H2X2S9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQyj-I-k95l38NIgKzv5J1-nz_dJcHUbE',
    appId: '1:286230054282:android:61efa276acb3d198a4f473',
    messagingSenderId: '286230054282',
    projectId: 'giziku-mobile',
    storageBucket: 'giziku-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ-OQwstWhKrE4UxDa2wt2r6d_dFakJd0',
    appId: '1:286230054282:ios:668f6e89f0ed33f9a4f473',
    messagingSenderId: '286230054282',
    projectId: 'giziku-mobile',
    storageBucket: 'giziku-mobile.firebasestorage.app',
    androidClientId: '286230054282-723d23otqnbh4fcpcuk7p1beb9cilkul.apps.googleusercontent.com',
    iosClientId: '286230054282-bvadj6dogipi4othu44cvck9h1o18fph.apps.googleusercontent.com',
    iosBundleId: 'com.example.giziku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ-OQwstWhKrE4UxDa2wt2r6d_dFakJd0',
    appId: '1:286230054282:ios:668f6e89f0ed33f9a4f473',
    messagingSenderId: '286230054282',
    projectId: 'giziku-mobile',
    storageBucket: 'giziku-mobile.firebasestorage.app',
    androidClientId: '286230054282-723d23otqnbh4fcpcuk7p1beb9cilkul.apps.googleusercontent.com',
    iosClientId: '286230054282-bvadj6dogipi4othu44cvck9h1o18fph.apps.googleusercontent.com',
    iosBundleId: 'com.example.giziku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDescekWWnJEVPdroRFUc3-RSPFhw8GzvQ',
    appId: '1:286230054282:web:ee51f3fae128bdc7a4f473',
    messagingSenderId: '286230054282',
    projectId: 'giziku-mobile',
    authDomain: 'giziku-mobile.firebaseapp.com',
    storageBucket: 'giziku-mobile.firebasestorage.app',
    measurementId: 'G-SYZRTTXFWS',
  );

}